version: '3.2'
services:
  mysql:
    volumes:
      - /Users/Shared/dockerData/mysql:/var/lib/mysql   #mac
    #          - /dockerData/mysql:/var/lib/mysql  #windows
    container_name: mysql-5.7
    image: mysql:5.7.25
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
  tsy:
    container_name: tsy_server
    image: edurekain/php5.5apache:latest

    ports:
      - 80:80
    #      - 443:443
    volumes:
      - ./php/php.ini:/etc/php5/apache2/php.ini:ro
      #       /s/docker/tsy/apache/conf/:/usr/local/apache2/conf/
      #      - /s/docker/tsy/www/:/var/www/html
      - ./php/www:/var/www/html
  #

volumes:
  sqldata:
