version: '3'
services:
  zabbix:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:alpine-4.4.7
    environment:
      DB_SERVER_HOST: 10.211.55.2
      DB_SERVER_PORT: 3306
      MYSQL_USER : root
      MYSQL_PASSWORD: 1234
    ports:
      - 10050:10050
      - 10051:10051
      - 80:80

      #docker run --name some-zabbix-server-mysql -e DB_SERVER_HOST="10.211.55.2" -e MYSQL_USER="root" -e MYSQL_PASSWORD="1234" -d zabbix/zabbix-server-mysql:alpine-4.4.7
      #docker logs some-zabbix-server-mysql
      #docker exec -ti some-zabbix-server-mysql /bin/bash