version: '3'
services:
  elasticseach:
    volumes:
      - /Users/Shared/dockerData/elasticseach:/usr/share/elasticsearch/data #mac
#     -  :/data #windows
    container_name: elasticsearch:6.5.4
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    ports:
      - 9200:9200
  kibana:
    #    volumes:
    #      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    container_name: local_kinana
    image: docker.elastic.co/kibana/kibana:6.5.4
    environment:
      SERVER_NAME: local.kibana
      ELASTICSEARCH_URL: http://localhost:9200/
    ports:
      - 5601:5601